# Generated by Django 4.2.6 on 2023-10-15 07:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('other_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('profile_url', models.TextField(blank=True, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('nin', models.CharField(blank=True, max_length=20, null=True)),
                ('nationality', models.CharField(default='Ugandan', max_length=255)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='O', max_length=25)),
                ('marital_status', models.CharField(blank=True, max_length=255, null=True)),
                ('staff_number', models.CharField(blank=True, max_length=50, null=True)),
                ('added_by', models.BigIntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=25, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('student_school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_school', to='school.school')),
            ],
        ),
    ]
