# Generated by Django 4.2.6 on 2023-10-15 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='staff_number',
            new_name='student_number',
        ),
    ]
