# Generated by Django 4.2.6 on 2023-10-15 07:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('short_name', models.CharField(blank=True, max_length=255, null=True)),
                ('registration_no', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, default='Uganda', max_length=255, null=True)),
                ('region', models.CharField(blank=True, choices=[('Central', 'Central'), ('Eastern', 'Eastern'), ('Western', 'Western'), ('Northern', 'Northern')], max_length=255, null=True)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('added_by', models.BigIntegerField(blank=True, null=True)),
                ('status', models.CharField(default='pending', max_length=25)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('logo_url', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
